# Dockerfile.mlapp

FROM python:3.9

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libatlas-base-dev \
    libpq-dev \
    gcc \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
# Copy app code
COPY . .
RUN pip install --no-cache-dir -r requirements.txt


# Logging directory
ENV LOG_DIR=/app/logs
RUN mkdir -p /app/logs

# Expose prediction API and training monitor ports
EXPOSE 9999
EXPOSE 8002

# Default: run the API
CMD ["python", "src/predict_api.py"]
