version: '3'

services:
  ml-app:
    build:
      context: .
      dockerfile: Dockerfile.mlapp
    container_name: app
    ports:
      - "9999:9999"
    volumes:
      - ./logs:/app/logs
      - ./data/processed:/app/data/processed
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8000
    depends_on:
      - mlflow
    networks:
      - ml-network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "8000:8000"
    volumes:
      - mlflow-data:/mlflow
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - ml-network
    depends_on:
      - ml-app

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - ml-network
    depends_on:
      - prometheus

networks:
  ml-network:
    driver: bridge

volumes:
  mlflow-data:
  prometheus-data:
  grafana-data:
