# Dockerfile.mlflow

FROM python:3.9

WORKDIR /mlflow

# System tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    libssl-dev \
    curl \
    git \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip & install MLflow
RUN pip install --upgrade pip setuptools wheel
RUN pip install mlflow pymysql

# Prepare volume directory
RUN mkdir -p /mlflow/mlruns


# Expose MLflow UI port
EXPOSE 8000

# Run MLflow server
CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "8000"]
