FROM python:3.9

WORKDIR /app

# Install system dependencies first
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libatlas-base-dev \
    libpq-dev \
    gcc \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the application code
COPY src/ ./src/
COPY models/ ./models/
COPY data/ ./data/
COPY configs/ ./configs/
COPY Makefile .
COPY src/ml_utils/ ./src/ml_utils/

# Set environment variable for logging
ENV LOG_DIR=/app/logs

RUN mkdir -p /app/logs

EXPOSE 9999

CMD ["python", "src/predict_api.py"]
